name: generate-changelog-action
description: Analyzes issues and milestones to generate markdown changelog.
author: Camptocamp Association
inputs:
  github_token:
    description: Github secret
    required: true
  write_to:
    description: Optional path to write the changelog to.
    required: false
outputs:
  changelog:
    description: Generated changelog in markdown format
runs:
  using: 'node16'
  main: 'dist/index.js'
