name: generate-changelog-action
description: Analyzes issues and milestones to generate markdown changelog.
author: Camptocamp Association
inputs:
  github_token:
    description: Github secret
    required: true
outputs:
  changelog:
    description: generated changelog in markdown format
runs:
  using: "node12"
  main: "dist/index.js"
